# Generated by Django 3.1.7 on 2021-03-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='creatd_at',
            new_name='created_at',
        ),
    ]
